# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REFjMrFucNfafCW0vR7jcVuO30ctVBXw
"""

!pip install tensorflow
!pip install keras
!pip install streamlit
!pip install pillow
!pip install numpy
!pip install opencv-python

import streamlit as st
from keras.models import load_model
from PIL import Image
import numpy as np
import cv2

# Load the model
model_path = 'emotion_model.hdf5'
try:
    model = load_model(model_path)
except Exception as e:
    st.error(f"Error loading model: {e}")

# Emotion labels
emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

# Streamlit app
st.title('Facial Expression Recognition')

# Upload image
uploaded_file = st.file_uploader("Upload an image", type=['jpg', 'png', 'jpeg'])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_column_width=True)

    # Convert to numpy array and preprocess
    image = np.array(image)
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    resized = cv2.resize(gray, (48, 48))
    normalized = resized / 255.0
    reshaped = np.reshape(normalized, (1, 48, 48, 1))

    # Predict emotion
    prediction = model.predict(reshaped)
    emotion = emotion_labels[np.argmax(prediction)]

    # Display prediction
    st.write(f"Predicted Emotion: **{emotion}**")

st.write("\nMade with ❤️ using Streamlit")